### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by artemklevtsov** [treeform/benchy#3]
Thank for the helpful package.

I would like to make some suggestions:
- use cpu warmup before measure
- use smaller units (or auto detect scale)
- combine measure and calculate ratio
- use stats module to calculate simple statistics
- use more robust statistics like a median or quantiles

I hope you will consider some of them.

May be useful:
- https://stackoverflow.com/a/66139156/1863950
- https://bravenewgeek.com/everything-you-know-about-latency-is-wrong/

**Comment by treeform** [comment]
Thank you for suggestions! Here are my thoughts:

* "use cpu warmup before measure" - I don't think this is needed, as I do outlier detection. If the first couple of runs are slow due to cpu warmup they will be thrown out. In my experience cpu warmup account for very little variance and you get huge outliers just randomly (probably due OS thread switching). Outlier detection is just a better tool vs this.

* "use smaller units (or auto detect scale)" - I like having everything be the same scale, but I can see how this can really help. I don't want to do this automatically though having used other benchmarking tools this really trips me up more then helps.

* "combine measure and calculate ratio" - Some thing best-in-group. I have though about adding some thing like this. Most stuff I measure are not directly comparable to each other.

* "use stats module" - I have my own statics module https://github.com/treeform/statistics but I also don't want to have dependencies - its simple statistics anyways.

* "use median or quantiles" -  I don't think median is that great. I can se some thing like 99% worse quantile or some thing. But really I have come to focus on minimum time. I like minimum time because its "the best case a run" because random out of control event like thread switch, random gc pause, cache evection ... did not mess up the numbers. I really like minimum time and that is what I usually use.

* https://stackoverflow.com/questions/66137351/performance-issue-when-call-isspaceascii/66139156#66139156 - I don't get what is so hard to measure. First they did not use a way to `keep` the results so compiler was free to optimize it a way. Second they are measuring very little code doing it 1000 times helps to get it up to speed. The `isSpaceAscii` is way slower because it's a system lib with {.rtc, extrenc.} that does not get optimized a way, while local `isSpace` does.

```nim
import strutils

proc isSpace(c: char): bool =
  result = c in Whitespace

timeIt "isSpaceAscii", 1000:
  for n in 0 .. 1000:
    for i in 1..255:
      let c = char(i)
      keep isSpaceAscii(c)

timeIt "isSpace", 1000:
  for n in 0 .. 1000:
    for i in 1..255:
      let c = char(i)
      keep isSpace(c)
```
```
name ............................... min time      avg time    std dv   runs
isSpaceAscii ....................... 0.281 ms      0.284 ms    ±0.003  x1000
isSpace ............................ 0.069 ms      0.071 ms    ±0.002  x1000
```

* https://bravenewgeek.com/everything-you-know-about-latency-is-wrong/ They talk bout the 99% worse quantile and it has some advantages over min time (0.0000% worse quantile?) mainly:

* Its more realistic of what users might encounter
* If other system depends on this thing finishing in X time.

But they are kind of bad for trying to get work done because:

* You end up measuring a ton of noise (task switches, cache flushes, gc pauses) which are mostly outside your control.
* You need to run it for longer to make sure to collect the noise, and you must collect it or suffer randomness! 
 
Example: you run your thing for 0.5 seconds once you get a good number, you think you made and improvement but its 0.5 seconds of measuring you get unlucky and a task switch which measures slower! You spend while trying to figure it out wasting time. After you realize this you run this thing for 1s, then for 5s measure sure all the noise stabilizes but OS events are fractal there is always bigger more rare bumps! I want benchmark results to come back quick so that I can get back to work and not try to tease out OS noise.

I don't like the 99% worse quantile for that reason.

**Comment by artemklevtsov** [comment]
Thank you very much for such detailed answer. You can close the issue if you think the question is settled.
